resources:
- name: concourse
  type: git
  source:
    uri: git@github.com:kthffmn/concourse.git
    branch: master
    private_key: {{private-repo-key}}
- name: slack-alert
  type: slack-notification
  source:
    url: {{slack-web-hook}}
jobs:
- name: run-tests
  plan:
  - get: concourse
    trigger: true
  - task: rails-test
    config:
      inputs:
      - name: concourse
      platform: linux
      image_resource:
        type: docker-image
        source:
          repository: ruby
          tag: 2.3.0
      run:
        path: ./concourse/run-rails-tests.sh
    on_failure:
      put: slack-alert
      params:
        text: Job failed!
        channel: '#cf_onboarding_labs'
        silent: true