resources:
- name: concourse
  type: git
  source:
    uri: git@github.com:kthffmn/concourse.git
    branch: master
    private_key: {{private-repo-key}}
jobs:
- name: run-tests
  plan:
  - get: concourse
    trigger: true
  - task: rails-test
    config:
      inputs:
      - name: concourse
      platform: linux
      image_resource:
        type: docker-image
        source:
          repository: kahoffman/ruby-node
      run:
        path: ./concourse/run-rails-tests.sh
