resources:
- name: concourse
  type: git
  source:
    uri: git@github.com:kthffmn/concourse.git
    branch: master
    private_key: {{private-repo-key}}

jobs:
- name: run-tests
  plan:
  - get: concourse
    trigger: true
  - task: say-hello
    config:
      inputs:
      - name: concourse
      platform: linux
      image_resource:
        type: docker-image
        source:
          repository: mwallasch/docker-ruby-node
          tag: 2.3.0
      run:
        path: ./concourse/run-rails-tests.sh
