resource_types:
- name: slack-notification
  type: docker-image
  source:
    repository: cfcommunity/slack-notification-resource
    tag: latest

resources:
- name: concourse
  type: git
  source:
    uri: git@github.com:kthffmn/concourse.git
    branch: master
    private_key: {{private-repo-key}}
- name: slack-alert
  type: slack-notification
  source:
    url: {{slack-web-hook}}
- name: tracker-output
  type: tracker
  source:
    token: {{private-tracker-token}}
    project_id: {{tracker-proj-id}}
    tracker_url: https://www.pivotaltracker.com

jobs:
- name: run-tests
  plan:
  - get: concourse
    trigger: true
  - task: rails-test
    config:
      inputs:
      - name: concourse
      platform: linux
      image_resource:
        type: docker-image
        source:
          repository: kahoffman/ruby-node
      run:
        path: ./concourse/run-rails-tests.sh
    on_failure:
      put: slack-alert
      params:
        text:  |
          The build failed. Check it out at:
          https://cf-onboarding-kentucky-ave.ci.cf-app.com/teams/$BUILD_TEAM_NAME/pipelines/$BUILD_PIPELINE_NAME/jobs/$BUILD_JOB_NAME/builds/$BUILD_NAME
        silent: true
  - put: tracker-output
    params: 
      repos: 
        - concourse