resources:
- name: concourse
  type: git
  source:
    uri: git@github.com:kthffmn/concourse.git
    branch: master
    private_key: {{private-repo-key}}

jobs:
- name: hello-world
  plan:
  - get: concourse
    trigger: true
  - task: say-hello
    config:
      inputs:
      - name: concourse
      image_resource:
        type: docker-image
        source:
          repository: ruby
          tag: 2.3.0
      run:
        path: ./concourse/say-hello.sh
